"""F6 — generate pitchkit docs (markdown manifest + self-contained HTML site) from source.

Scans every feature .py under pitchkit/pitchkit, extracts the module-docstring summary and
the `# === Quality & when to use ===` block, and emits:
  - FEATURES.md          (a manifest table — one row per feature file)
  - docs/site/index.html (self-contained: sidebar nav, collapsible cards, search, dark mode)

Run:  python -m pitchkit.docs.build_docs
Stays in sync with the code — re-run after adding a feature.
"""
from __future__ import annotations

import ast
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]  # .../pitchkit/pitchkit
PROJECT = PKG.parent                        # .../pitchkit
FEATURE_FOLDERS = ["core", "detection", "tracking", "calibration", "events", "stats",
                   "tactics", "reliability", "viz", "pipeline"]


def _summary(text: str) -> str:
    m = ast.get_docstring(ast.parse(text))
    return (m or "").strip().splitlines()[0] if (m or "").strip() else "(no docstring)"


def _quality_block(text: str) -> str:
    out, capturing = [], False
    for ln in text.splitlines():
        if "# === Quality & when to use" in ln:
            capturing = True
            continue
        if capturing:
            s = ln.lstrip()
            if s.startswith("#"):
                out.append(s[2:] if s.startswith("# ") else s[1:])
            else:
                break
    return "\n".join(out).strip()


def collect():
    rows = []
    for folder in FEATURE_FOLDERS:
        d = PKG / folder
        if not d.is_dir():
            continue
        for py in sorted(d.glob("*.py")):
            if py.name == "__init__.py":
                continue
            text = py.read_text(encoding="utf-8")
            rows.append({"folder": folder, "file": py.name, "path": f"{folder}/{py.name}",
                         "summary": _summary(text), "quality": _quality_block(text)})
    return rows


def write_markdown(rows) -> Path:
    out = PROJECT / "FEATURES.md"
    lines = ["# pitchkit — feature manifest", "",
             "Auto-generated by `pitchkit/docs/build_docs.py`. One row per feature file.", "",
             "| Folder | File | Summary |", "|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['folder']} | `{r['file']}` | {r['summary']} |")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


_HTML_TEMPLATE = """<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>pitchkit — framework docs</title>
<style>
:root{--bg:#0f1115;--fg:#e7e9ee;--muted:#9aa3b2;--accent:#36f;--card:#161922;--bd:#262b36}
@media (prefers-color-scheme: light){:root{--bg:#fafafa;--fg:#161922;--muted:#5b6472;--accent:#14f;--card:#fff;--bd:#e3e6ee}}
*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--fg);line-height:1.5}
.layout{display:grid;grid-template-columns:260px 1fr;max-width:1200px;margin:0 auto}
aside{position:sticky;top:0;align-self:start;max-height:100vh;overflow:auto;padding:18px;border-right:1px solid var(--bd)}
aside h1{font-size:1.1rem;margin:.2rem 0 .6rem}aside a{display:block;color:var(--muted);text-decoration:none;padding:3px 6px;border-radius:6px;font-size:.85rem}
aside a:hover{background:var(--card);color:var(--fg)}.nav-group summary{font-weight:600;margin:8px 0 4px;color:var(--fg)}
main{padding:24px}header{margin-bottom:18px}header .meta{color:var(--muted);font-size:.9rem}
pre{background:var(--card);border:1px solid var(--bd);padding:12px;border-radius:8px;white-space:pre-wrap;font-size:.8rem;color:var(--muted)}
.card{background:var(--card);border:1px solid var(--bd);border-radius:10px;padding:14px 16px;margin-bottom:12px}
.card h2{font-size:1rem;margin:0 0 4px}.card h2 span{color:var(--muted)}
.summary{color:var(--muted);margin:0 0 8px;font-size:.92rem}
details summary{cursor:pointer;color:var(--accent);font-size:.85rem}
code{background:var(--card);border:1px solid var(--bd);padding:1px 5px;border-radius:5px;font-size:.85em}
.toolbar{position:fixed;right:16px;bottom:16px;display:flex;gap:8px}
.toolbar button{background:var(--accent);color:#fff;border:0;border-radius:8px;padding:8px 12px;cursor:pointer;font-size:.85rem}
#search{width:100%;margin:6px 0;padding:6px;border-radius:6px;border:1px solid var(--bd);background:var(--card);color:var(--fg)}
.pipe{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.pipe span{background:var(--card);border:1px solid var(--bd);border-radius:20px;padding:4px 12px;font-size:.8rem}
@media print{aside,.toolbar{display:none}.layout{grid-template-columns:1fr}}
</style></head><body>
<div class="toolbar"><button onclick="window.print()">Print</button></div>
<div class="layout"><aside>
<h1>pitchkit</h1>
<input id="search" placeholder="filter features..." oninput="filterCards()">
__NAV__
</aside><main>
<header><h1>pitchkit &mdash; standalone football video-analytics framework</h1>
<div class="meta">Video &rarr; tracking, events, physical/tactical stats, viz. __N__ feature files. Self-contained &amp; copyable.</div>
<div class="pipe"><span>detect</span>&rarr;<span>track</span>&rarr;<span>ball</span>&rarr;<span>teams</span>&rarr;<span>events</span>&rarr;<span>stats</span></div>
<pre>from pitchkit.pipeline.default import run, run_feature
res = run("football-1.mp4", max_frames=50)         # full pipeline
res.value["data"]["stats"]; res.value["failed"]    # outputs + any failures
run_feature("detect", "football-1.mp4")            # isolate one stage</pre>
</header>
__CARDS__
</main></div>
<script>
function filterCards(){var q=document.getElementById('search').value.toLowerCase();
document.querySelectorAll('.card').forEach(function(c){c.style.display=(c.innerText.toLowerCase().indexOf(q)>-1)?'':'none'});}
</script>
</body></html>"""


def _esc(s: str) -> str:
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def write_html(rows) -> Path:
    by_folder = {}
    for r in rows:
        by_folder.setdefault(r["folder"], []).append(r)
    nav = "\n".join(
        '<details class="nav-group" open><summary>' + f + "</summary>" +
        "".join(f'<a href="#{f}-{r["file"]}">{r["file"]}</a>' for r in items) +
        "</details>"
        for f, items in by_folder.items()
    )
    cards = "\n".join(
        f'<section class="card" id="{r["folder"]}-{r["file"]}"><h2>{r["folder"]}/<span>{r["file"]}</span></h2>'
        f'<p class="summary">{_esc(r["summary"])}</p>'
        f'<details><summary>Quality &amp; when to use</summary><pre>{_esc(r["quality"]) or "(see source)"}</pre></details>'
        f'</section>'
        for r in rows
    )
    html = _HTML_TEMPLATE.replace("__NAV__", nav).replace("__CARDS__", cards).replace("__N__", str(len(rows)))
    out_dir = PROJECT / "docs" / "site"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "index.html"
    out.write_text(html, encoding="utf-8")
    return out


def main():
    rows = collect()
    md = write_markdown(rows)
    html = write_html(rows)
    print(f"wrote {md} ({len(rows)} features)")
    print(f"wrote {html}")


if __name__ == "__main__":
    main()
